"""initial migration

Revision ID: 142b6f0432dd
Revises: None
Create Date: 2015-07-21 14:12:24.855031

"""

# revision identifiers, used by Alembic.
revision = '142b6f0432dd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
