"""users. email & confirmed added

Revision ID: 17e098e2e132
Revises: 142b6f0432dd
Create Date: 2015-07-27 18:33:51.945998

"""

# revision identifiers, used by Alembic.
revision = '17e098e2e132'
down_revision = '142b6f0432dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
