"""quiz data models relations fix

Revision ID: 1e662b2e8f87
Revises: 4b4d452ab345
Create Date: 2015-08-21 20:20:00.857593

"""

# revision identifiers, used by Alembic.
revision = '1e662b2e8f87'
down_revision = '4b4d452ab345'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
