"""quiz data models relations fix

Revision ID: 3141176408c1
Revises: fb996d0e9a6
Create Date: 2015-08-21 19:46:30.660529

"""

# revision identifiers, used by Alembic.
revision = '3141176408c1'
down_revision = 'fb996d0e9a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
