"""Permissions set changed

Revision ID: 372020ccafda
Revises: 53a30e112e29
Create Date: 2015-08-21 21:16:04.555029

"""

# revision identifiers, used by Alembic.
revision = '372020ccafda'
down_revision = '53a30e112e29'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
