"""user model additional info

Revision ID: 499426781938
Revises: 142b6f0432dd
Create Date: 2015-08-13 18:18:24.940407

"""

# revision identifiers, used by Alembic.
revision = '499426781938'
down_revision = '142b6f0432dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'organization')
    ### end Alembic commands ###
