"""quiz data models relations fix

Revision ID: 4b4d452ab345
Revises: 3141176408c1
Create Date: 2015-08-21 19:52:03.452069

"""

# revision identifiers, used by Alembic.
revision = '4b4d452ab345'
down_revision = '3141176408c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
