"""quiz data association table fix

Revision ID: 53a30e112e29
Revises: 1e662b2e8f87
Create Date: 2015-08-21 20:43:54.557813

"""

# revision identifiers, used by Alembic.
revision = '53a30e112e29'
down_revision = '1e662b2e8f87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
