"""quiz data models relations fix

Revision ID: fb996d0e9a6
Revises: 22abb6308899
Create Date: 2015-08-21 19:43:41.517176

"""

# revision identifiers, used by Alembic.
revision = 'fb996d0e9a6'
down_revision = '22abb6308899'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
